export const CSV_BUYERS = [
  {
    "id": "582525000001145016",
    "name": "Nikhil Gems",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "INR",
    "gstin": "27AKFPJ0990D1ZB",
    "gstTreatment": "business_gst",
    "billingAddress": "",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": false,
    "shippingAddress": "110, 19th Floor, Dariya Mahal A, Nepeansea Road, Mumbai, Maharashtra\nIndia 400006",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.287Z"
  },
  {
    "id": "582525000001157005",
    "name": "Atyahara",
    "company": "Atyahara",
    "email": "manavjhaveri01@gmail.com",
    "phone": "9619248797",
    "currency": "INR",
    "gstin": "27BCVPJ2000F1ZU",
    "gstTreatment": "business_gst",
    "billingAddress": "110, 19 Floor, Dariya Mahal A, Nepeansea Road, Mumbai, Maharashtra\nIndia 400006",
    "billingCity": "Mumbai",
    "billingState": "Maharashtra",
    "country": "India",
    "shippingSameAsBilling": true,
    "shippingAddress": "110, 19 Floor, Dariya Mahal A, Nepeansea Road, Mumbai, Maharashtra\nIndia 400006",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001164001",
    "name": "AhhhMuse",
    "company": "AhhhMuse",
    "email": "ttt@ahhhmuse.com",
    "phone": "5753134070",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "2340 US Hwy 180 E. #171,, SILVER CITY, New Mexico\nU.S.A 88061",
    "billingCity": "SILVER CITY",
    "billingState": "New Mexico",
    "country": "U.S.A",
    "shippingSameAsBilling": true,
    "shippingAddress": "2340 US Hwy 180 E. #171,, SILVER CITY, New Mexico\nU.S.A 88061",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001170053",
    "name": "Oasis De Cristal Inc",
    "company": "Oasis De Cristal Inc",
    "email": "",
    "phone": "",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": false,
    "shippingAddress": "315- 950 RUE NOTRE DAME OUEST  MONTREAL, Montreal, Quebec\nCanada H3C0K3",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001199001",
    "name": "Gem Drop Shop",
    "company": "Gem Drop Shop",
    "email": "",
    "phone": "",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "104 Broadway Street, Black Mountain, North Carolina\nU.S.A 28711",
    "billingCity": "Black Mountain",
    "billingState": "North Carolina",
    "country": "U.S.A",
    "shippingSameAsBilling": true,
    "shippingAddress": "104 Broadway Street, Black Mountain, North Carolina\nU.S.A 28711",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001212001",
    "name": "Yong, Liu",
    "company": "",
    "email": "1622455907@qq.com",
    "phone": "15380260608",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "Floor 1, Hall 2, Crystal City, Donghai County, Lianyungang, Jiangsu\nChina",
    "billingCity": "Lianyungang",
    "billingState": "Jiangsu",
    "country": "China",
    "shippingSameAsBilling": true,
    "shippingAddress": "Floor 1, Hall 2, Crystal City, Donghai County, Lianyungang, Jiangsu\nChina",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001288003",
    "name": "Salaudin",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "business_none",
    "billingAddress": "#78 E W S, 2nd Stage, Hanumantha Nagar, Bannimantap, VTC: Mysore, Mysore, Karnataka\nIndia 570015",
    "billingCity": "Mysore",
    "billingState": "Karnataka",
    "country": "India",
    "shippingSameAsBilling": true,
    "shippingAddress": "#78 E W S, 2nd Stage, Hanumantha Nagar, Bannimantap, VTC: Mysore, Mysore, Karnataka\nIndia 570015",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001309001",
    "name": "Rocks for the Spirit",
    "company": "Rocks for the Spirit",
    "email": "bri@rocksforthespirit.com",
    "phone": "8586630378",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "2033 San Elijo Ave #474, Cardiff, California\nU.S.A 920007",
    "billingCity": "Cardiff",
    "billingState": "California",
    "country": "U.S.A",
    "shippingSameAsBilling": true,
    "shippingAddress": "2033 San Elijo Ave #474, Cardiff, California\nU.S.A 920007",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001309019",
    "name": "Helms Co., Ltd",
    "company": "Helms Co., Ltd",
    "email": "helmsimport@helms-kk.co.jp",
    "phone": "'+81455010818",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.295Z"
  },
  {
    "id": "582525000001418003",
    "name": "Ashley Laicona",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "14816 Daley Ln NA WOODBRIDGE VA UNITED STATES 22193",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "14816 Daley Ln NA WOODBRIDGE VA UNITED STATES 22193",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001435001",
    "name": "Hegyekristaly Asvanybolt",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001520009",
    "name": "Oasis De Cristal",
    "company": "Oasis De Cristal",
    "email": "oasisdecristal.inc@gmail.com",
    "phone": "5146996989",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "315- 950 Rue Notre Dame, Ouest Montreal, Montreal, Montreal, Quebec\nCanada H3C0K3",
    "billingCity": "Montreal",
    "billingState": "Quebec",
    "country": "Canada",
    "shippingSameAsBilling": false,
    "shippingAddress": "Canada",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001535007",
    "name": "Matsyaa Crystals",
    "company": "Matsyaa Crystals",
    "email": "",
    "phone": "90196-29998",
    "currency": "INR",
    "gstin": "29APRPV7020H1ZA",
    "gstTreatment": "business_gst",
    "billingAddress": "G16, Gem Plaza, 66 Infantry Road, Bangalore 560001\nIndia",
    "billingCity": "",
    "billingState": "",
    "country": "India",
    "shippingSameAsBilling": false,
    "shippingAddress": "G16, Gem Plaza, 66 Infantry Road, Bangalore 560001",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001623001",
    "name": "Original Way Crystals LLC",
    "company": "Original Way Crystals LLC",
    "email": "originalcrystals@gmail.com",
    "phone": "'+18056965744",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "1270 W 2320 S, STE A, West Valley City, Utah\nU.S.A 84119",
    "billingCity": "West Valley City",
    "billingState": "Utah",
    "country": "U.S.A",
    "shippingSameAsBilling": true,
    "shippingAddress": "1270 W 2320 S, STE A, West Valley City, Utah\nU.S.A 84119",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001642001",
    "name": "NPO Ashoro Fossil and Nature",
    "company": "NPO Ashoro Fossil and Nature",
    "email": "saw@ashoromuseum.com",
    "phone": "",
    "currency": "JPY",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "Konan 1-29, Ashoro-Cho, Hokkaido\nJapan 089-3727",
    "billingCity": "Hokkaido",
    "billingState": "",
    "country": "Japan",
    "shippingSameAsBilling": true,
    "shippingAddress": "Konan 1-29, Ashoro-Cho, Hokkaido\nJapan 089-3727",
    "portLading": "TOKYO",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001652001",
    "name": "Celestique Crystals",
    "company": "Celestique Crystals",
    "email": "",
    "phone": "'+1 (310) 717-7767",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "11777 San Vicente Blvd\nSte 500, Los Angeles, California\nU.S.A 90049",
    "billingCity": "Los Angeles",
    "billingState": "California",
    "country": "U.S.A",
    "shippingSameAsBilling": true,
    "shippingAddress": "11777 San Vicente Blvd\nSte 500, Los Angeles, California\nU.S.A 90049",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001682001",
    "name": "Poppie Crystals",
    "company": "",
    "email": "joulianna4221@gmail.com",
    "phone": "65 8261 1711",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "509A Wellington Circle #08-99 751509\nSingapore",
    "billingCity": "",
    "billingState": "",
    "country": "Singapore",
    "shippingSameAsBilling": true,
    "shippingAddress": "509A Wellington Circle #08-99 751509\nSingapore",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001706005",
    "name": "Marvelous Gems MTY. LTD",
    "company": "Marvelous Gems MTY. LTD",
    "email": "",
    "phone": "",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "Unit 23-24, 8F, Block B,, 21 Man Lok Street,, Hung Hom Kowloon\nHong Kong",
    "billingCity": "Hung Hom Kowloon",
    "billingState": "",
    "country": "Hong Kong",
    "shippingSameAsBilling": false,
    "shippingAddress": "Red Lion Inn, Room 160/161, 222 S Freeway Road, Tucson, Arizona\nU.S.A 85745",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001723001",
    "name": "Sovereign Gems",
    "company": "Sovereign Gems",
    "email": "erin@sovereigngems.com",
    "phone": "",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "Suite 5, Level 1, 428 George Street, Sydney, New South Wales\nAustralia 2000",
    "billingCity": "Sydney",
    "billingState": "New South Wales",
    "country": "Australia",
    "shippingSameAsBilling": true,
    "shippingAddress": "Suite 5, Level 1, 428 George Street, Sydney, New South Wales\nAustralia 2000",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001763001",
    "name": "Carmelo",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "EUR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001847001",
    "name": "Gojko Balta",
    "company": "",
    "email": "",
    "phone": "'+381 64 1111073",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001872600",
    "name": "Takehito",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000001950003",
    "name": "Willow Co. Ltd",
    "company": "Willow Co. Ltd",
    "email": "",
    "phone": "'+81-351482381",
    "currency": "JPY",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "Seigetudo Bld., 5 F, 7-16-15 Ginza,Chuo-ku\nTokyo. 1040061\nJapan.\nJapan",
    "billingCity": "",
    "billingState": "",
    "country": "Japan",
    "shippingSameAsBilling": false,
    "shippingAddress": "Red Lion Inn,\n222 S Freeway St, Tucson, Arizona, 85745\nU.S.A",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000002029077",
    "name": "BANYAVIRAG KFT.",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "EUR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "1 SZECHENYI STREET, DEBRECEN, HUNGARY\nHungary 4025",
    "billingCity": "HUNGARY",
    "billingState": "",
    "country": "Hungary",
    "shippingSameAsBilling": true,
    "shippingAddress": "1 SZECHENYI STREET, DEBRECEN, HUNGARY\nHungary 4025",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000002033003",
    "name": "WAKOU BUSSAN CO.,LTD",
    "company": "WAKOU BUSSAN CO.,LTD",
    "email": "info@wakou-stone.co.jp",
    "phone": "",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "WAKOU BUSSAN CO.,LTD\nC/O MAKOTO KIKUCHI\n18-10 IWAKIRI-IRIYAMA, MIYAGINO-KU SENDAI, JAPAN\n983-0821",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "WAKOU BUSSAN CO.,LTD\nC/O MAKOTO KIKUCHI\n18-10 IWAKIRI-IRIYAMA, MIYAGINO-KU SENDAI, JAPAN\n983-0821",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000002061003",
    "name": "emma",
    "company": "",
    "email": "",
    "phone": "",
    "currency": "INR",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "United Kingdom",
    "billingCity": "",
    "billingState": "",
    "country": "United Kingdom",
    "shippingSameAsBilling": true,
    "shippingAddress": "United Kingdom",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000002062055",
    "name": "Willow Co",
    "company": "Willow Co",
    "email": "",
    "phone": "",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "SEIGETUDO BLD, 5 F, 7-16-15 GINZA\nCHUO-KU\nJAPAN - 104-0061",
    "billingCity": "",
    "billingState": "",
    "country": "",
    "shippingSameAsBilling": true,
    "shippingAddress": "SEIGETUDO BLD, 5 F, 7-16-15 GINZA\nCHUO-KU\nJAPAN - 104-0061",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  },
  {
    "id": "582525000002094005",
    "name": "Wegner Crystal Mines",
    "company": "Wegner Crystal Mines",
    "email": "wegner@ipa.net",
    "phone": "",
    "currency": "USD",
    "gstin": "",
    "gstTreatment": "overseas",
    "billingAddress": "82 WEGNER RANCH ROAD, Mount IDA, Arkansas\nU.S.A 71957",
    "billingCity": "Mount IDA",
    "billingState": "Arkansas",
    "country": "U.S.A",
    "shippingSameAsBilling": true,
    "shippingAddress": "82 WEGNER RANCH ROAD, Mount IDA, Arkansas\nU.S.A 71957",
    "portLading": "",
    "notes": "",
    "createdAt": "2026-03-15T18:44:59.296Z"
  }
];
